name: 'Version for Publishing'
description: 'Creates a version string from package file'
branding:
  color: orange
  icon: cloud
inputs:
  branch:
    description: 'Branch of current execution'
    required: false
    default: 'main'
  filePath:
    description: 'Path to json file with version key'
    required: false
    default: 'package.json'
outputs:
  version:
    description: 'Generated version number string'
runs:
  using: 'node12'
  main: 'dist/index.js'
